sync benchmarks

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -15,6 +15,10 @@ on:
       - labeled # benchmarks label required
   workflow_dispatch:
 
+env: 
+  DEPLOY_BRANCH: main
+  TARDIS_VER: release-2024.08.25 # master 
+
 concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
   cancel-in-progress: true
@@ -23,15 +27,21 @@ defaults:
   run:
     shell: bash -l {0}
 
-env:
-  TARDIS_VER: release-2024.08.25 # master 
+
 jobs:
+  test-cache:
+    uses: ./.github/workflows/lfs-cache.yml
+    with:
+      regression-data-repo: tardis-sn/tardis-regression-data
+      allow_lfs_pull: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'git-lfs-pull') }}
+
   build:
     if: github.event_name == 'push' ||
       github.event_name == 'workflow_dispatch' ||
       (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'benchmarks'))
     runs-on: ubuntu-latest
+    needs: [test-cache]
     steps:
       - uses: actions/checkout@v4
         if: github.event_name != 'pull_request'
@@ -97,7 +107,7 @@ jobs:
         if: github.event_name != 'pull_request'
         run: |
           git log -n 5 --pretty=format:"%H" >> tag_commits.txt
-          asv run --show-stderr -v HASHFILE:tag_commits.txt | tee asv-output.log
+          asv run -a --show-stderr rounds=1 HASHFILE:tag_commits.txt | tee asv-output.log
           if grep -q failed asv-output.log; then 
             echo "Some benchmarks have failed!"
             exit 1
@@ -113,45 +123,101 @@ jobs:
 
       - name: Push results to dest repo
         if: github.event_name != 'pull_request'
-        continue-on-error: true
-        uses: cpina/github-action-push-to-another-repository@main
-        env:
-          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN }}
+        uses: peaceiris/actions-gh-pages@v4
         with:
-          source-directory: ".asv"
-          destination-github-username: "tardis-sn"
-          destination-repository-name: "stardis-benchmarks"
-          user-email: tardis.sn.bot@gmail.com
-          target-branch: main
-          target-directory: .asv
-          
-      - name: Compare HEAD with main if PR
+          personal_token: ${{ secrets.BOT_TOKEN }}
+          publish_branch: ${{ env.DEPLOY_BRANCH }}
+          publish_dir: .asv/html
+          keep_files: true
+          external_repository: tardis-sn/stardis-benchmarks
+          user_name: "TARDIS Bot"
+          user_email: "tardis.sn.bot@gmail.com"
+
+      - name: Run benchmarks for base and head commits of PR
         if: github.event_name == 'pull_request'
-        continue-on-error: true # TODO: step failed sporadically while testing
         run: |
-          asv continuous ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-cont-output.log  
-          if grep -q failed asv-cont-output.log; then 
-            echo "Some benchmarks have errors!"
+          echo $(git rev-parse HEAD) > commit_hashes.txt
+          echo $(git rev-parse main) >> commit_hashes.txt
+          asv run -a rounds=1 HASHFILE:commit_hashes.txt | tee asv-output-PR.log  
+          if grep -q failed asv-output-PR.log; then 
+            echo "Some benchmarks have failed!"
             exit 1
           fi
 
-      - name: Compare Master and PR head
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-compare-output.log
+      - name: Compare Main and PR head
+        run: asv compare origin/main HEAD --factor 1.1 --split --sort ratio | tee asv-compare-output.log
 
-      - name: Compare Master and PR head but only show changed results
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed | tee asv-compare-changed-output.log
+      - name: Compare Main and PR head but only show changed results
+        run: asv compare origin/main HEAD --only-changed --factor 1.1 --split --sort ratio | tee asv-compare-changed-output.log
 
-      - name: asv output 1
+      - name: Benchmarks compare output
         id: asv_pr_vs_main
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-output.log
 
-      - name: asv output 2
+      - name: Benchmarks compare only changed output
         id: asv_pr_vs_main_changed
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
+
+      - name: Generate Graphs and HTML of PR
+        if: github.event_name == 'pull_request'
+        run: |
+          asv publish
+
+      - name: Delete env files of PR
+        if: github.event_name == 'pull_request'
+        run: rm -r .asv/env
+
+      - name: Set destination directory
+        if: github.event_name == 'pull_request'
+        run: |
+          BRANCH=$(echo ${GITHUB_REF#refs/heads/})
+          if [[ $EVENT == push ]] || [[ $EVENT == workflow_dispatch ]]; then
+            if [[ $BRANCH == $DEFAULT ]]; then
+              echo "DEST_DIR=" >> $GITHUB_ENV
+            else
+              echo "DEST_DIR=branch/$BRANCH" >> $GITHUB_ENV
+            fi
+          elif [[ $EVENT == pull_request ]]; then
+            echo "DEST_DIR=pull/$PR" >> $GITHUB_ENV
+          else
+            echo "Unexpected event trigger $EVENT"
+            exit 1
+          fi
+          cat $GITHUB_ENV
+        env:
+          DEFAULT: ${{ github.event.repository.default_branch }}
+          EVENT: ${{ github.event_name }}
+          PR: ${{ github.event.number }}
+
+      - name: Set clean branch option
+        if: github.event_name == 'pull_request'
+        run: |
+          if [[ $EVENT == workflow_dispatch ]]; then
+            echo "CLEAN_BRANCH=true" >> $GITHUB_ENV
+          else
+            echo "CLEAN_BRANCH=false" >> $GITHUB_ENV
+          fi
+          cat $GITHUB_ENV
+        env:
+          EVENT: ${{ github.event_name }}
+
+      - name: Deploy ${{ env.DEST_DIR }}
+        if: github.event_name == 'pull_request'
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          personal_token: ${{ secrets.BOT_TOKEN }}
+          publish_branch: ${{ env.DEPLOY_BRANCH }}
+          publish_dir: .asv/html
+          destination_dir: ${{ env.DEST_DIR }}
+          keep_files: true
+          force_orphan: ${{ env.CLEAN_BRANCH }}
+          external_repository: tardis-sn/stardis-benchmarks
+          user_name: "TARDIS Bot"
+          user_email: "tardis.sn.bot@gmail.com"
 
       - name: Find Comment
         if: always() && github.event_name == 'pull_request'
@@ -176,6 +242,7 @@ jobs:
             I ran benchmarks as you asked comparing main (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
             Here are the logs produced by ASV.
             Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
+
             Significantly changed benchmarks:
             <details>
 
@@ -193,8 +260,11 @@ jobs:
               ```
               
             </details>
+
+            If you want to see the graph of the results, you can check it [**here**](${{ env.URL_PAGES }})
         env:
           URL: https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}?check_suite_focus=true
+          URL_PAGES: https://tardis-sn.github.io/stardis-benchmarks/pull/${{ github.event.number }}
 
       - name: Save results artifact
         uses: actions/upload-artifact@v4
@@ -203,6 +273,5 @@ jobs:
           name: asv-benchmark-results-${{ runner.os }}
           path: |
             .asv/results
-            asv-cont-output.log  
             asv-compare-output.log
             asv-compare-changed-output.log
